Add NOAA-21 support
pytroll/pyorbital pull request #118
Opened 2023-02-15 09:52 UTC by adybbroe

This PR is adding NOAA-21 to the list of designators/ids in the built in platforms.txt file

This was actually already included in #113 but that PR is about environment variables and is also not yet ready and merged.

 - [ ] Closes #xxxx 
 - [ ] Tests added 
 - [ ] Tests passed 
 - [ ] Passes ``flake8 pyorbital`` 
 - [ ] Fully documented

2023-02-15 12:41 UTC, adybbroe commented
While working with this PR and upgrading our systems for NOAA-21 at SMHI we realized that there seem to be a bug here, standing in the way of updating support for NOAA-21, see #119 
So, perhaps this PR should try fix this as well?

2024-11-23 11:21 UTC, adybbroe commented on pyorbital/tests/test_tlefile.py
> +line1_2 = "1 38771U 12049A   21137.30264622  .00000000  00000+0 -49996-5 0 00017"
```suggestion
```

2024-11-23 11:22 UTC, adybbroe commented on pyorbital/tests/test_tlefile.py
> +line1_2 = "1 38771U 12049A   21137.30264622  .00000000  00000+0 -49996-5 0 00017"
```suggestion
```

2024-11-23 11:22 UTC, adybbroe commented on pyorbital/tests/test_tlefile.py
> +line2_2 = "2 38771  98.7162 197.7716 0002383 106.1049 122.6344 14.21477797449453"
```suggestion
```

2024-11-23 11:30 UTC, adybbroe commented on pyorbital/tests/test_tlefile.py
```suggestion
LINE1_2 = "1 38771U 12049A   21137.30264622  .00000000  00000+0 -49996-5 0 00017"
LINE2_2 = "2 38771  98.7162 197.7716 0002383 106.1049 122.6344 14.21477797449453"
```

2024-11-23 13:43 UTC, adybbroe commented
I have come to the conclusion that there is really no serious issue easily solved as otherwise suggested in #119 
Either the user specify a WMO Oscar based satellite name matching what is in the `platforms.txt`, so `NOAA-21` (already in main) or the user must specify an exact match to what is written in the TLE files. So if the TLE files look like this:

```
NOAA 21 (JPSS-2)        
1 54234U 22150A   23045.56664999  .00000332  00000+0  17829-3 0  9993
2 54234  98.7059 345.5113 0001226  81.6523 278.4792 14.19543871 13653
```

The use must specify `NOAA 21 (JPSS-2)` as the platform name, as in:
`tle_jpss2 = tlefile.read('NOAA 21 (JPSS-2)', './jpss2.tle')`

The only thing this PR does now is to add a debug message indicating that there might be a match in the TLE file for the the satellite the user is wanting the TLEs for. So, like:
```
>>> tle_metop = tlefile.read('Metop', '/data/tles/tle-202409060015.txt')
[DEBUG: 2024-11-23 14:30:03 : pyorbital.tlefile] Path to the Pyorbital configuration (where e.g. platforms.txt is found): /home/a000680/usr/src/forks/pyorbital/pyorbital/etc
[DEBUG: 2024-11-23 14:30:03 : pyorbital.tlefile] Found a possible match: METOP-B?
[DEBUG: 2024-11-23 14:30:03 : pyorbital.tlefile] Found a possible match: METOP-C?
```
And:
```
>>> tle_n21 = tlefile.read('NOAA 21', './jpss2.tle')
[DEBUG: 2024-11-23 14:38:15 : pyorbital.tlefile] Path to the Pyorbital configuration (where e.g. platforms.txt is found): /home/a000680/usr/src/forks/pyorbital/pyorbital/etc
[DEBUG: 2024-11-23 14:38:15 : pyorbital.tlefile] Found a possible match: NOAA 21 (JPSS-2)?
```

It means that in case the user gives a name like "NOAA" or "Metop" or even "N" or something far from a real satellite name, there might be several debug messages with more or less useful suggestions. But I think that can be accepted.

Okay?

2024-11-25 13:39 UTC, pnuu commented on pyorbital/tlefile.py
> +        LOGGER.debug("Found a possible match: %s?", str(l_0.strip()))
I'm wondering should there be something other than just the log message here? The tests pass, but :man_shrugging:

2024-11-25 13:40 UTC, pnuu requested changes
Umm, this PR currently actually does only do refactoring and not add the mentioned NOAA-21 to the platforms.txt. So `git commit` missing @adybbroe ?

2024-11-25 13:44 UTC, adybbroe commented
> Umm, this PR currently actually does only do refactoring and not add the mentioned NOAA-21 to the platforms.txt. So `git commit` missing @adybbroe ?

Yeah right, after a long discussion (mainly with myself) it ended up differently from what I anticipated when I started. Should we rename it then? I am okay with that!

2024-11-25 15:12 UTC, adybbroe commented
> Umm, this PR currently actually does only do refactoring and not add the mentioned NOAA-21 to the platforms.txt. So `git commit` missing @adybbroe ?

Better now @pnuu ?

2024-11-26 06:44 UTC, pnuu commented on pyorbital/tlefile.py
> +        LOGGER.debug("Found a possible match: %s?", str(l_0.strip()))
Nope, just wanted to solve the pre-commit complaint and afterwards got confused about the former title and description of the issue :sweat_smile:

2024-11-26 06:45 UTC, pnuu commented
> Better now @pnuu ?

Much better! Now the title and description match what's being changed :+1:

2024-11-27 07:24 UTC, mraspaud reviewed
LGTM!

2024-11-27 08:18 UTC, merged